name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
       matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
    - name: checkout source code
      uses: actions/checkout@v1
    - id: setmatrix
      run: |
        shopt -s nullglob
        matrixArray=(./lambdas/*) # Creates array of files
        matrixObject=`
         jq -Rnc '
          ( input | split(" ") ) as $vals |
          [[$vals] | transpose[] | { "lambdafile": .[0] }]
          ' <<<${matrixArray[@]} | jq "{ \"include\": . }"
        `
        # echo "::set-output name=matrix::${matrixArray[@]}" # echo converted array to space separated string
        echo "::set-output name=matrix::{\"include\":[{\"lambdafile\":\"./example1/lambdafile1.js\"},{\"lambdafile\":\"./example2/lambdafile2.js\"}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
     - name: checkout source code
       uses: actions/checkout@v1
     - run: echo ${{ matrix.lambdafile }}
