name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
       matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
    - name: checkout source code
      uses: actions/checkout@v1
    - id: setmatrix
      run: |
        shopt -s nullglob
        matrixArray=(./lambdas/*) # Creates array of files
        matrixArray=`echo ${matrixArray[@]}` # Convert to space separated string
        echo "::set-output name=matrix::$matrixArray"
  job2:
    needs: job1
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         lambdafile:${{ needs.job1.outputs.matrix }} (`echo ${matrixArray[@]}`)
    steps:
     - name: checkout source code
       uses: actions/checkout@v1
     - run: echo "${{ needs.job1.outputs.matrix }}"
     - run: echo ${{ matrix.lambdafile }}
